[package]
name = "chip-8"
version = "0.1.0"
authors = ["Opadc <1986646750@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ggez = "0.5.1"
anyhow = "1.0.35"